// Module for generating the generator regulator signal.

// Pin definitions
const int GENERATOR_PWM_PIN = 5;

// Generator parameters
int pwmFrequency = 1000; // PWM frequency in Hz
extern int pwmDutyCycle; // Defined in main.ino

void setupGenerator() {
  // Arduino's analogWrite frequency on pin 5 is ~976 Hz by default, which is close enough for many applications.
  // For custom frequencies, timer manipulation would be needed, but we'll start with the default.
  pinMode(GENERATOR_PWM_PIN, OUTPUT);
}

void loopGenerator() {
  // The PWM signal is generated by analogWrite, so the loop doesn't need to do anything
  // unless we are in an automatic mode that adjusts duty cycle based on other parameters.
}

void setGeneratorDutyCycle(int dutyCycle) {
  if (dutyCycle >= 0 && dutyCycle <= 100) {
    pwmDutyCycle = dutyCycle;
    // Map duty cycle from 0-100 to 0-255 for analogWrite
    int pwmValue = map(pwmDutyCycle, 0, 100, 0, 255);
    analogWrite(GENERATOR_PWM_PIN, pwmValue);
  }
}
