#ifndef CONFIG_H
#define CONFIG_H

#define FIRMWARE_VERSION "2.0.0"
#define DEFAULT_SERIAL_BAUD 115200

#define DEFAULT_RPM 1000
#define DEFAULT_INJECTOR_PULSE_US 3000
#define DEFAULT_IGNITION_DWELL_US 3000

#endif // CONFIG_H
